#pragma once
#include <algorithm>
#include <array>
#include <ctime> 
#include <numeric>
#include <map>
#include <iostream>
#include <string>
#include <cstdlib> 
#include <random>
#include <chrono>
#include <Windows.h>